-- Your SQL goes here
CREATE TABLE category (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    alias       TEXT NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO category (id, name, alias) VALUES
(1, 'Info Utama', 'MAIN');

SELECT setval((SELECT pg_get_serial_sequence('category','id')), 1, true);
