-- Your SQL goes here
CREATE TABLE roles (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    alias       TEXT NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO roles (id, name, alias) VALUES
(1, 'Admin',       'ADMIN'),
(2, 'Tim Redaksi', 'EDITORIAL'),
(3, 'Member',      'MEMBER');

SELECT setval((SELECT pg_get_serial_sequence('roles','id')), 3, true);
